title: Mithun
author: Mithun Koroth
email: mithunrajan@gmail.com
description: > # this means to ignore newlines until "github_username:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# social links
github_username:  mkoroth
rss: rss
show_excerpts: true
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html
tipue_search:
  include:
    pages: true

